# Generated by Django 4.2.30 on 2026-05-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Servico', max_length=200)),
                ('tagline', models.CharField(default='Home services, on demand.', max_length=200)),
                ('support_email', models.EmailField(default='support@servico.com', max_length=254)),
                ('support_phone', models.CharField(default='+880-1700-000000', max_length=20)),
                ('visiting_fee', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('urgent_surcharge', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('bkash_number', models.CharField(blank=True, default='', max_length=20)),
                ('nagad_number', models.CharField(blank=True, default='', max_length=20)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'site_settings',
            },
        ),
    ]
