# Generated by Django 4.2.30 on 2026-05-11 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('nid_number', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('experience_years', models.CharField(max_length=10)),
                ('skills', models.JSONField(default=list)),
                ('bio', models.TextField(blank=True)),
                ('availability', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('flexible', 'Flexible')], default='full_time', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('reject_reason', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='provider_avatars/')),
                ('total_jobs', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'provider_applications',
            },
        ),
        migrations.CreateModel(
            name='ProviderEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_label', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('processing', 'Processing'), ('scheduled', 'Scheduled')], default='scheduled', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='providers.providerapplication')),
            ],
            options={
                'db_table': 'provider_earnings',
                'ordering': ['-period_start'],
            },
        ),
    ]
