# Generated by Django 4.2.30 on 2026-05-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerapplication',
            name='nid_file',
            field=models.FileField(blank=True, null=True, upload_to='nid_files/'),
        ),
    ]
