# Generated by Django 4.2.30 on 2026-05-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='merchant_account',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
